/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.IOException;

public class AppTest {
    //crap I don't know how I would go about writing test for this app....

    @Test public void testApiPing() throws IOException {

        // test that we are getting a string back from the api
//      String testString = App.pingApi();
//       System.out.println(testString.charAt(0));
//       assertEquals('{', testString.charAt(0));
    }
}
