/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.stream.JsonReader;

import java.io.*;
import java.util.ArrayList;
import java.util.Random;

public class App {

    public static void main(String[] args) throws Exception {
        try{
            System.out.println(qouteOfTheDay());
        }catch(Exception e){
            System.out.println("had a issue");
        }
    }


    public static String qouteOfTheDay() throws Exception {
        File file = new File("src/main/resources/recentqoutes.json" );
        JsonReader jsReader = new JsonReader(new FileReader(file));

        ArrayList<Qoute> arrayOfQuotes = new ArrayList<>();

        //--------------------------------------
        // This block of code is thanks to Peyton who cracked the docs to figure out how to make this work
        jsReader.beginArray();       // look for beginning of array char [
        while(jsReader.hasNext()){   // check to make sure another obj exist
            String author = null;    // reset variable to null
            String text = null;

            jsReader.beginObject();  // look for beginning of obj char {
            while(jsReader.hasNext()){ // check that another line exist in obj
                String name = jsReader.nextName(); // store next key in variable
                if(name.equals("author"))          // check if key matches a key we need for constructor
                    author = jsReader.nextString();// if found store value in variable
                else if(name.equals("text"))
                    text = jsReader.nextString();
                else
                    jsReader.skipValue(); // if not a key we need skip
            }
            jsReader.endObject();        // look for end of obj char }
            Qoute qoute = new Qoute(text, author); // create new quote with variables
            arrayOfQuotes.add(qoute);// add quote to array
        }
        jsReader.endArray();
        jsReader.close();
//---------------------------------------------------
       Random rand = new Random();
       int index = rand.nextInt(arrayOfQuotes.size());


    return arrayOfQuotes.get(index).toString();
    }
}
